name: flitch
description: Anime Dart, Web Scrapper and API Client to allow streaming animes

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_modular:
  flutter_i18n:
  outline_material_icons:
  sqflite:
  path:
  country_pickers:
  get_it:
  path_provider:
  shared_preferences:
  equatable:
  vector_math:
  dartz:
  dio:
  diacritic:
  flutter_dotenv:

  # Flutter deps
  flutter:
    sdk: flutter
  cupertino_icons:

dev_dependencies:
  effective_dart:
  test:
  dotenv:
  process_run:

  # Flutter deps
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
