name: anime_dart
description: Anime Dart, Web Scrapper and API Client to allow streaming animes

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter_modular: ^2.0.1
  flutter_i18n: ^0.20.1
  outline_material_icons: ^0.1.1
  sqflite: ^1.3.2+2
  path: ^1.7.0
  country_pickers: ^1.3.0
  get_it: ^5.0.6
  path_provider: ^1.6.27
  shared_preferences: ^0.5.12+4
  equatable: ^1.2.5
  vector_math: ^2.0.8
  dartz: ^0.9.2
  dio: ^3.0.10
  search: ^0.3.0
  database: ^0.3.3
  diacritic: ^0.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.15.7
  commit_formatter:
    git: https://github.com/LaksCastro/commit-formatter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
