name: app_core
description: Anime Dart, Web Scrapper and API Client to allow streaming animes

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  dartz: ^0.9.2
  dio: ^3.0.10

  # Flutter deps
  flutter_dotenv: ^3.1.0
  flutter:
    sdk: flutter

  # Local deps
  app_utils:
    path: ../utils

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.15.7
  dotenv: ^2.0.0

  # Flutter deps
  flutter_test:
    sdk: flutter

  # Local deps
  commit_formatter:
    git: https://github.com/LaksCastro/commit-formatter
