name: app_utils
description: Utils for any Dart enviroment

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  diacritic: ^0.1.1

dev_dependencies:
  effective_dart: ^1.3.0
  commit_formatter:
    git: https://github.com/LaksCastro/commit-formatter
  test: ^1.15.7
